---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: be-gitops-config
  namespace: p4-dev
spec:
  templateSource:
    uri: https://github.com/greenpeace-hack/gp-node-be.git
    ref: master
  triggers:
  - type: Change
  - type: Periodic
    cron: "@hourly"
  serviceAccountRef: gitops-runner
  templateProcessorImage: quay.io/kohlstechnology/eunomia-applier:v0.0.1
  resourceHandlingMode: None
  resourceDeletionMode: None
