---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-runner
  namespace: p4-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eunomia-runner-binding
  namespace: p4-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: gitops-runner
  namespace: p4-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eunomia-runner-binding
  namespace: p4-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: gitops-runner
  namespace: p4-dev
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: ui-gitops-config
  namespace: p4-dev
spec:
  templateSource:
    uri: https://github.com/greenpeace-hack/gp-frontend.git
    ref: master
  triggers:
  - type: Change
  - type: Periodic
    cron: "* * * * *"
  serviceAccountRef: gitops-runner
  templateProcessorImage: quay.io/kohlstechnology/eunomia-applier:v0.0.1
  resourceHandlingMode: None
  resourceDeletionMode: None
